# Generated by Django 2.2.9 on 2021-12-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211219_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
